name: new_project
description: A new Flutter project

# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none'

# The following defines the version and build number for your application.
version: 1.0.0+1

environment:
  sdk: '>=3.4.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  http: ^0.13.3
  cached_network_image: ^3.2.0
  provider: ^6.0.2
  cupertino_icons: ^1.0.6
  carousel_slider: ^4.0.0
  url_launcher: ^6.1.7
  webview_flutter: ^4.0.1
  flutter_launcher_icons: ^0.9.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter_icons:
  android: true
  ios: true
  image_path: "assets/images/playstore.png"

flutter:
  uses-material-design: true

  assets:
    - assets/images/news.png
    - assets/images/politics.png
    - assets/images/crypto.png
    - assets/images/technology.png
    - assets/images/music.png
    - assets/images/gaming.png
    - assets/images/anime.png
    - assets/images/sports.png
    - assets/images/travel.png
    - assets/images/healthcare.png
